tasks:
  - init: 'echo "TODO: Replace with init/build command"'
    command: 
      yarn global add @quasar/cli && export PATH="$(yarn global bin):$PATH" && cd /workspace/quasar-limon/quasar-limon && yarn install
